---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dnvk9le825kl/public_html/pnrconverter.roamingnepal.com/
    - /bin/rsync -a --delete --exclude='.git' --exclude='config/settings.php' --exclude='assets/images/airlines/' ./ $DEPLOYPATH
    - /bin/rsync -a assets/images/airlines/ $DEPLOYPATH/assets/images/airlines/
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
